### ISSUE TITLE
_smpl.obj for the scans

### ISSUE THREAD

**Issue by tyluann** [bharat-b7/LoopReg#4]
Another question, sorry...

The corresponding smpl model of the scan is also required in data loader. So should I that use a T-pose SMPL mesh or I have to acquire some kinds of raw initialization of the certain scan?

**Comment by bharat-b7** [comment]
For supervised warm-start, you need registered SMPL model for training scans.
For self-supervised training, you don't need registered SMPL.

**Comment by tyluann** [comment]
so if I want to test a given scan (I only have the scanned mesh), I should run warmup_PartSpecificNet.py first, right?

**Comment by bharat-b7** [comment]
For testing with pre-trained model you just need to run `train_PartSpecificNet.py` with `-mode val`.

**Comment by tyluann** [comment]
I try that and find in dataloader, it needs a corresponding smpl mesh for the scan.

    def __getitem__(self, idx):
        path = self.data[idx]
        name = split(path)[1]

        **input_smpl = Mesh(filename=join(path, name + '_smpl.obj'))**
        if self.naked:
            input_scan = Mesh(filename=join(path, name + '_smpl.obj'))
        else:
            input_scan = Mesh(filename=join(path, name + '.obj'))

so how do I acquire this _smpl.obj?

**Comment by bharat-b7** [comment]
For testing you don't need this. Just comment it out.

**Comment by tyluann** [comment]
Okay, Many thanks

**Comment by Bingoang** [comment]
@bharat-b7 
Hi, I really appreciate your great work!

I ran the test command but the output was nothing:
`$ python train_PartSpecificNet.py 1 -batch_size 12 -split_file assets/data_split_01.pkl -mode val -save_name corr -naked`
Using BLB SMPL from the project: LoopReg
Not initializing with pre-trained supervised correspondence network
Cache folder:  cache/1616901030
Loaded checkpoint from: /home/ang/LoopReg-main/models/../experiments/combined_net/naked_exp_id_1/checkpoints/checkpoint_epoch_163.tar
Testing with epoch 163
0it [00:00, ?it/s]

if I have a scan mesh/ pointcould, where should I set the input path? and the output should be a .obj, right?
Hope you can give me some advice~

Best wishes
