### ISSUE TITLE
'spread_SMPL_function.py' error

### ISSUE THREAD

**Issue by Luciano07** [bharat-b7/LoopReg#9]
Hi,
I'm trying to use 'spread_SMPL_function.py' to spread smpl in voxel grid, and save it in *.pkl files. 
I changed paths to pkl smpl models and run, but it fails before save 'posedirs.pkl'.
Here is my output:
![Screenshot from 2021-03-23 16-58-27](https://user-images.githubusercontent.com/26660371/112210147-1a57a080-8bf9-11eb-9bc5-eb688e930e24.png)
After that i tried to uncomment line 79:
```python
assert closest_points == barycentric_interpolation(smpl_mesh.v[vert_ids], bary_coords)
```
and seems like is something wrong in interpolation:
![Screenshot from 2021-03-23 17-01-32](https://user-images.githubusercontent.com/26660371/112210438-728ea280-8bf9-11eb-965e-ad1ea298e62b.png)
Is there something i can do to solve it? 
I'm using Ubuntu 18.04, python 3.6.9 and pytorch 1.4.0

Thanks for share your work!

**Comment by Luciano07** [comment]
I think is memory limitation error, I'll try with a better hardware.

**Comment by bharat-b7** [comment]
You can reduce the size of the cube from 64^3 to 32^3 and see if that solves the memory problem.

**Comment by Luciano07** [comment]
Thanks! with 'res=32' it works.
